name: Build
on:
  push:

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - name: Build
        run: |
          nix-build -j auto
